// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimNextJob = `-- name: ClaimNextJob :one
WITH claimed AS (
    SELECT id
    FROM jobs
    WHERE status = 'QUEUED'
      AND (scheduled_at IS NULL OR scheduled_at <= NOW())
    ORDER BY priority DESC NULLS LAST, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs
SET status = 'RUNNING',
    lease_expires_at = $1,
    updated_at = NOW()
WHERE id IN (SELECT id FROM claimed)
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

func (q *Queries) ClaimNextJob(ctx context.Context, leaseExpiresAt *time.Time) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextJob, leaseExpiresAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs
SET status = 'COMPLETED',
    result = $2,
    error = NULL,
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

type CompleteJobParams struct {
	ID     uuid.UUID       `json:"id"`
	Result json.RawMessage `json:"result"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.Result)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (run_id, step, payload)
VALUES ($1, $2, $3)
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

type CreateJobParams struct {
	RunID   uuid.UUID       `json:"run_id"`
	Step    string          `json:"step"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.RunID, arg.Step, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const createJobEvent = `-- name: CreateJobEvent :one
INSERT INTO job_events (job_id, event_type, data)
VALUES ($1, $2, $3)
RETURNING id, job_id, event_type, data, created_at
`

type CreateJobEventParams struct {
	JobID     uuid.UUID       `json:"job_id"`
	EventType string          `json:"event_type"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, createJobEvent, arg.JobID, arg.EventType, arg.Data)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.EventType,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE jobs
SET status = $2,
    error = $3,
    attempt_count = attempt_count + 1,
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

type FailJobParams struct {
	ID     uuid.UUID `json:"id"`
	Status JobStatus `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, failJob, arg.ID, arg.Status, arg.Error)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const findExpiredLeases = `-- name: FindExpiredLeases :many
SELECT id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
FROM jobs
WHERE status = 'RUNNING'
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at < NOW()
`

func (q *Queries) FindExpiredLeases(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, findExpiredLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxRetries,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
			&i.LeaseExpiresAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :one
UPDATE jobs
SET lease_expires_at = $2
WHERE id = $1
  AND status = 'RUNNING'
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

type HeartbeatJobParams struct {
	ID             uuid.UUID  `json:"id"`
	LeaseExpiresAt *time.Time `json:"lease_expires_at"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, heartbeatJob, arg.ID, arg.LeaseExpiresAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, event_type, data, created_at
FROM job_events
WHERE job_id = $1
ORDER BY created_at
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EventType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRun = `-- name: ListJobsByRun :many
SELECT id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
FROM jobs
WHERE run_id = $1
ORDER BY created_at
`

func (q *Queries) ListJobsByRun(ctx context.Context, runID uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxRetries,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
			&i.LeaseExpiresAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteRetries = `-- name: PromoteRetries :many
UPDATE jobs
SET status = 'QUEUED',
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE status = 'RETRYING'
  AND scheduled_at IS NOT NULL
  AND scheduled_at <= NOW()
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

func (q *Queries) PromoteRetries(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, promoteRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxRetries,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
			&i.LeaseExpiresAt,
			&i.Result,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueJob = `-- name: RequeueJob :one
UPDATE jobs
SET status = 'QUEUED',
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, step, payload, status, priority, attempt_count, max_retries, scheduled_at, created_at, updated_at, run_id, lease_expires_at, result, error
`

func (q *Queries) RequeueJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, requeueJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxRetries,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
		&i.LeaseExpiresAt,
		&i.Result,
		&i.Error,
	)
	return i, err
}
