// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type JobStatus string

const (
	JobStatusCREATED    JobStatus = "CREATED"
	JobStatusQUEUED     JobStatus = "QUEUED"
	JobStatusPICKEDUP   JobStatus = "PICKED_UP"
	JobStatusRUNNING    JobStatus = "RUNNING"
	JobStatusCOMPLETED  JobStatus = "COMPLETED"
	JobStatusFAILED     JobStatus = "FAILED"
	JobStatusRETRYING   JobStatus = "RETRYING"
	JobStatusDEADLETTER JobStatus = "DEAD_LETTER"
	JobStatusCANCELLED  JobStatus = "CANCELLED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCREATED,
		JobStatusQUEUED,
		JobStatusPICKEDUP,
		JobStatusRUNNING,
		JobStatusCOMPLETED,
		JobStatusFAILED,
		JobStatusRETRYING,
		JobStatusDEADLETTER,
		JobStatusCANCELLED:
		return true
	}
	return false
}

type RunStatus string

const (
	RunStatusPENDING   RunStatus = "PENDING"
	RunStatusRUNNING   RunStatus = "RUNNING"
	RunStatusCOMPLETED RunStatus = "COMPLETED"
	RunStatusFAILED    RunStatus = "FAILED"
	RunStatusCANCELLED RunStatus = "CANCELLED"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusPENDING,
		RunStatusRUNNING,
		RunStatusCOMPLETED,
		RunStatusFAILED,
		RunStatusCANCELLED:
		return true
	}
	return false
}

type WorkflowStatus string

const (
	WorkflowStatusActive   WorkflowStatus = "active"
	WorkflowStatusInactive WorkflowStatus = "inactive"
)

func (e *WorkflowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowStatus(s)
	case string:
		*e = WorkflowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowStatus: %T", src)
	}
	return nil
}

type NullWorkflowStatus struct {
	WorkflowStatus WorkflowStatus `json:"workflow_status"`
	Valid          bool           `json:"valid"` // Valid is true if WorkflowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowStatus), nil
}

func (e WorkflowStatus) Valid() bool {
	switch e {
	case WorkflowStatusActive,
		WorkflowStatusInactive:
		return true
	}
	return false
}

type Job struct {
	ID             uuid.UUID       `json:"id"`
	Step           string          `json:"step"`
	Payload        json.RawMessage `json:"payload"`
	Status         JobStatus       `json:"status"`
	Priority       *int32          `json:"priority"`
	AttemptCount   *int32          `json:"attempt_count"`
	MaxRetries     *int32          `json:"max_retries"`
	ScheduledAt    *time.Time      `json:"scheduled_at"`
	CreatedAt      *time.Time      `json:"created_at"`
	UpdatedAt      *time.Time      `json:"updated_at"`
	RunID          uuid.UUID       `json:"run_id"`
	LeaseExpiresAt *time.Time      `json:"lease_expires_at"`
	Result         json.RawMessage `json:"result"`
	Error          *string         `json:"error"`
}

type JobEvent struct {
	ID        uuid.UUID       `json:"id"`
	JobID     uuid.UUID       `json:"job_id"`
	EventType string          `json:"event_type"`
	Data      json.RawMessage `json:"data"`
	CreatedAt *time.Time      `json:"created_at"`
}

type Worker struct {
	ID            uuid.UUID  `json:"id"`
	Hostname      string     `json:"hostname"`
	Status        string     `json:"status"`
	CurrentJobID  *uuid.UUID `json:"current_job_id"`
	LastHeartbeat *time.Time `json:"last_heartbeat"`
}

type Workflow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Status      WorkflowStatus  `json:"status"`
	Config      json.RawMessage `json:"config"`
	CreatedAt   *time.Time      `json:"created_at"`
	UpdatedAt   *time.Time      `json:"updated_at"`
}

type WorkflowRun struct {
	ID         uuid.UUID  `json:"id"`
	WorkflowID uuid.UUID  `json:"workflow_id"`
	Status     RunStatus  `json:"status"`
	Error      *string    `json:"error"`
	CreatedAt  *time.Time `json:"created_at"`
	FinishedAt *time.Time `json:"finished_at"`
}
