// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteWorkflow(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ListWorkflows(ctx context.Context) ([]Workflow, error)
}

var _ Querier = (*Queries)(nil)
