// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const completeRun = `-- name: CompleteRun :one
UPDATE workflow_runs
SET status = 'COMPLETED',
    finished_at = NOW()
WHERE id = $1
RETURNING id, workflow_id, status, error, created_at, finished_at
`

func (q *Queries) CompleteRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, completeRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO workflow_runs (workflow_id, status)
VALUES ($1, 'RUNNING')
RETURNING id, workflow_id, status, error, created_at, finished_at
`

func (q *Queries) CreateRun(ctx context.Context, workflowID uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createRun, workflowID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failRun = `-- name: FailRun :one
UPDATE workflow_runs
SET status = 'FAILED',
    error = $2,
    finished_at = NOW()
WHERE id = $1
RETURNING id, workflow_id, status, error, created_at, finished_at
`

type FailRunParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, failRun, arg.ID, arg.Error)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, workflow_id, status, error, created_at, finished_at
FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunsByWorkflow = `-- name: ListRunsByWorkflow :many
SELECT id, workflow_id, status, error, created_at, finished_at
FROM workflow_runs
WHERE workflow_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRunsByWorkflow(ctx context.Context, workflowID uuid.UUID) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listRunsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
